//! Desktop GUI (eframe/egui).
//!
//! Layout: input files -> output settings -> run. Files can also be dropped
//! onto the window. The conversion runs on a worker thread and reports back
//! over a channel so the UI stays responsive.

use blf_decoder::convert::{
    ConvertOptions, OutputLayout, Progress, Summary, TimestampMode, convert,
};
use blf_decoder::export::OutputFormat;
use eframe::egui;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::sync::mpsc::{Receiver, channel};
use std::time::Duration;

const APP_VERSION: &str = env!("CARGO_PKG_VERSION");

pub fn run() -> eframe::Result<()> {
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_inner_size([640.0, 480.0])
            .with_min_inner_size([560.0, 420.0])
            .with_icon(window_icon()),
        ..Default::default()
    };
    eframe::run_native(
        "BLF Decoder",
        options,
        Box::new(|cc| {
            let japanese = install_cjk_font(&cc.egui_ctx);
            cc.egui_ctx.all_styles_mut(|style| {
                style.spacing.item_spacing = egui::vec2(8.0, 8.0);
                style.spacing.button_padding = egui::vec2(12.0, 6.0);
            });
            Ok(Box::new(App::new(japanese)))
        }),
    )
}

/// Window/taskbar icon, embedded as raw 64x64 RGBA generated by
/// `scripts/gen_icon.py` (the .exe file icon comes from build.rs instead).
fn window_icon() -> egui::IconData {
    egui::IconData {
        rgba: include_bytes!("../assets/icon_64.rgba").to_vec(),
        width: 64,
        height: 64,
    }
}

/// Try to load a system font with Japanese glyph coverage. egui's built-in
/// fonts have no CJK glyphs, so without this the UI falls back to English.
fn install_cjk_font(ctx: &egui::Context) -> bool {
    const CANDIDATES: &[&str] = &[
        // Windows (primary target)
        "C:\\Windows\\Fonts\\meiryo.ttc",
        "C:\\Windows\\Fonts\\YuGothM.ttc",
        "C:\\Windows\\Fonts\\msgothic.ttc",
        // macOS
        "/System/Library/Fonts/Hiragino Sans GB.ttc",
        // Linux
        "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
        "/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc",
        "/usr/share/fonts/opentype/ipafont-gothic/ipag.ttf",
    ];
    for path in CANDIDATES {
        let Ok(bytes) = std::fs::read(path) else {
            continue;
        };
        let mut fonts = egui::FontDefinitions::default();
        fonts.font_data.insert(
            "cjk".to_owned(),
            Arc::new(egui::FontData::from_owned(bytes)),
        );
        for family in [egui::FontFamily::Proportional, egui::FontFamily::Monospace] {
            if let Some(list) = fonts.families.get_mut(&family) {
                list.push("cjk".to_owned());
            }
        }
        ctx.set_fonts(fonts);
        return true;
    }
    false
}

/// UI strings, Japanese when a CJK-capable font is available.
struct Labels {
    section_input: &'static str,
    section_output: &'static str,
    blf_file: &'static str,
    dbc_file: &'static str,
    out_dir: &'static str,
    format: &'static str,
    layout: &'static str,
    layout_resample: &'static str,
    layout_raw: &'static str,
    interval_suffix: &'static str,
    timestamp: &'static str,
    ts_relative: &'static str,
    ts_epoch: &'static str,
    browse: &'static str,
    convert: &'static str,
    converting: &'static str,
    frames_unit: &'static str,
    open_folder: &'static str,
    drop_hint: &'static str,
    done: fn(&Summary) -> String,
    error_prefix: &'static str,
    not_selected: &'static str,
}

const JA: Labels = Labels {
    section_input: "入力",
    section_output: "出力",
    blf_file: "BLF ファイル",
    dbc_file: "DBC ファイル",
    out_dir: "出力フォルダ",
    format: "ファイル形式",
    layout: "データ形状",
    layout_resample: "等間隔サンプリング(前値ホールド)",
    layout_raw: "フレーム単位(生データ)",
    interval_suffix: " ms",
    timestamp: "時刻列",
    ts_relative: "先頭からの経過秒",
    ts_epoch: "UNIX エポック秒",
    browse: "選択...",
    convert: "変換",
    converting: "変換中...",
    frames_unit: "フレーム",
    open_folder: "出力フォルダを開く",
    drop_hint: "ヒント: BLF / DBC ファイルはウィンドウへのドラッグ&ドロップでも指定できます",
    done: |s| {
        format!(
            "変換が完了しました\n出力: {}\n{} 行を書き出し(デコード {} / {} フレーム、信号 {} 列)",
            s.output_path.display(),
            s.rows_written,
            s.frames_decoded,
            s.frames_read,
            s.signal_columns
        )
    },
    error_prefix: "エラー: ",
    not_selected: "(未選択)",
};

const EN: Labels = Labels {
    section_input: "Input",
    section_output: "Output",
    blf_file: "BLF file",
    dbc_file: "DBC file",
    out_dir: "Output folder",
    format: "File format",
    layout: "Table shape",
    layout_resample: "Fixed interval (sample & hold)",
    layout_raw: "Per frame (raw)",
    interval_suffix: " ms",
    timestamp: "Timestamp",
    ts_relative: "Seconds from start",
    ts_epoch: "Unix epoch seconds",
    browse: "Browse...",
    convert: "Convert",
    converting: "Converting...",
    frames_unit: "frames",
    open_folder: "Open output folder",
    drop_hint: "Tip: you can also drag & drop BLF / DBC files onto this window",
    done: |s| {
        format!(
            "Conversion finished\nOutput: {}\n{} rows written (decoded {} of {} frames, {} signal columns)",
            s.output_path.display(),
            s.rows_written,
            s.frames_decoded,
            s.frames_read,
            s.signal_columns
        )
    },
    error_prefix: "Error: ",
    not_selected: "(not selected)",
};

enum WorkerMsg {
    Progress(Progress),
    Finished(Result<Summary, String>),
}

enum State {
    Idle,
    Running {
        progress: Progress,
        rx: Receiver<WorkerMsg>,
    },
    Done(Summary),
    Failed(String),
}

struct App {
    labels: &'static Labels,
    blf_path: Option<PathBuf>,
    dbc_path: Option<PathBuf>,
    out_dir: Option<PathBuf>,
    format: OutputFormat,
    layout: OutputLayout,
    interval_ms: f64,
    timestamp: TimestampMode,
    state: State,
}

impl App {
    fn new(japanese: bool) -> Self {
        Self {
            labels: if japanese { &JA } else { &EN },
            blf_path: None,
            dbc_path: None,
            out_dir: None,
            format: OutputFormat::Csv,
            layout: OutputLayout::Resampled,
            interval_ms: 100.0,
            timestamp: TimestampMode::RelativeSeconds,
            state: State::Idle,
        }
    }

    fn start_conversion(&mut self) {
        let (Some(blf), Some(dbc), Some(out)) = (
            self.blf_path.clone(),
            self.dbc_path.clone(),
            self.out_dir.clone(),
        ) else {
            return;
        };
        let options = ConvertOptions {
            format: self.format,
            layout: self.layout,
            resample_ms: self.interval_ms,
            timestamp: self.timestamp,
        };
        let (tx, rx) = channel();
        std::thread::spawn(move || {
            let mut on_progress = |p: Progress| {
                let _ = tx.send(WorkerMsg::Progress(p));
            };
            let result =
                convert(&blf, &dbc, &out, options, &mut on_progress).map_err(|e| format!("{e:#}"));
            let _ = tx.send(WorkerMsg::Finished(result));
        });
        self.state = State::Running {
            progress: Progress::default(),
            rx,
        };
    }

    fn poll_worker(&mut self) {
        if let State::Running { progress, rx } = &mut self.state {
            let mut finished = None;
            while let Ok(msg) = rx.try_recv() {
                match msg {
                    WorkerMsg::Progress(p) => *progress = p,
                    WorkerMsg::Finished(result) => finished = Some(result),
                }
            }
            if let Some(result) = finished {
                self.state = match result {
                    Ok(summary) => State::Done(summary),
                    Err(message) => State::Failed(message),
                };
            }
        }
    }

    /// Assign files dropped onto the window by extension.
    fn handle_dropped_files(&mut self, ctx: &egui::Context) {
        let dropped: Vec<PathBuf> = ctx.input(|i| {
            i.raw
                .dropped_files
                .iter()
                .filter_map(|f| f.path.clone())
                .collect()
        });
        for path in dropped {
            match path
                .extension()
                .and_then(|e| e.to_str())
                .map(|e| e.to_ascii_lowercase())
                .as_deref()
            {
                Some("blf") => self.blf_path = Some(path),
                Some("dbc") => self.dbc_path = Some(path),
                _ if path.is_dir() => self.out_dir = Some(path),
                _ => {}
            }
        }
    }

    fn path_row(
        ui: &mut egui::Ui,
        label: &str,
        browse: &str,
        not_selected: &str,
        path: &mut Option<PathBuf>,
        enabled: bool,
        pick: impl Fn() -> Option<PathBuf>,
    ) {
        ui.label(label);
        match path {
            Some(p) => {
                let file = p
                    .file_name()
                    .map(|n| n.to_string_lossy().into_owned())
                    .unwrap_or_else(|| p.display().to_string());
                ui.add(egui::Label::new(egui::RichText::new(file).strong()).truncate())
                    .on_hover_text(p.display().to_string());
            }
            None => {
                ui.add(egui::Label::new(egui::RichText::new(not_selected).weak()).truncate());
            }
        }
        if ui.add_enabled(enabled, egui::Button::new(browse)).clicked()
            && let Some(picked) = pick()
        {
            *path = Some(picked);
        }
        ui.end_row();
    }
}

impl eframe::App for App {
    fn ui(&mut self, ui: &mut egui::Ui, _frame: &mut eframe::Frame) {
        self.poll_worker();
        self.handle_dropped_files(&ui.ctx().clone());
        let labels = self.labels;
        let running = matches!(self.state, State::Running { .. });
        if running {
            ui.ctx().request_repaint_after(Duration::from_millis(100));
        }

        egui::CentralPanel::default().show(ui, |ui| {
            ui.horizontal(|ui| {
                ui.heading("BLF Decoder");
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    ui.label(egui::RichText::new(format!("v{APP_VERSION}")).weak());
                });
            });
            ui.label(egui::RichText::new(labels.drop_hint).weak().small());
            ui.add_space(4.0);

            // ---- Input files ----
            ui.group(|ui| {
                ui.set_width(ui.available_width());
                ui.label(egui::RichText::new(labels.section_input).strong());
                egui::Grid::new("inputs")
                    .num_columns(3)
                    .spacing([12.0, 8.0])
                    .min_col_width(90.0)
                    .show(ui, |ui| {
                        Self::path_row(
                            ui,
                            labels.blf_file,
                            labels.browse,
                            labels.not_selected,
                            &mut self.blf_path,
                            !running,
                            || {
                                rfd::FileDialog::new()
                                    .add_filter("BLF", &["blf"])
                                    .pick_file()
                            },
                        );
                        Self::path_row(
                            ui,
                            labels.dbc_file,
                            labels.browse,
                            labels.not_selected,
                            &mut self.dbc_path,
                            !running,
                            || {
                                rfd::FileDialog::new()
                                    .add_filter("DBC", &["dbc"])
                                    .pick_file()
                            },
                        );
                    });
            });

            // ---- Output settings ----
            ui.group(|ui| {
                ui.set_width(ui.available_width());
                ui.label(egui::RichText::new(labels.section_output).strong());
                egui::Grid::new("outputs")
                    .num_columns(3)
                    .spacing([12.0, 8.0])
                    .min_col_width(90.0)
                    .show(ui, |ui| {
                        Self::path_row(
                            ui,
                            labels.out_dir,
                            labels.browse,
                            labels.not_selected,
                            &mut self.out_dir,
                            !running,
                            || rfd::FileDialog::new().pick_folder(),
                        );

                        ui.label(labels.format);
                        ui.horizontal(|ui| {
                            ui.add_enabled_ui(!running, |ui| {
                                ui.radio_value(&mut self.format, OutputFormat::Csv, "CSV");
                                ui.radio_value(&mut self.format, OutputFormat::Parquet, "Parquet");
                            });
                        });
                        ui.label("");
                        ui.end_row();

                        ui.label(labels.layout);
                        ui.vertical(|ui| {
                            ui.add_enabled_ui(!running, |ui| {
                                ui.horizontal(|ui| {
                                    ui.radio_value(
                                        &mut self.layout,
                                        OutputLayout::Resampled,
                                        labels.layout_resample,
                                    );
                                    ui.add_enabled(
                                        self.layout == OutputLayout::Resampled,
                                        egui::DragValue::new(&mut self.interval_ms)
                                            .range(1.0..=60_000.0)
                                            .speed(10)
                                            .suffix(labels.interval_suffix),
                                    );
                                });
                                ui.radio_value(
                                    &mut self.layout,
                                    OutputLayout::PerFrame,
                                    labels.layout_raw,
                                );
                            });
                        });
                        ui.label("");
                        ui.end_row();

                        ui.label(labels.timestamp);
                        ui.horizontal(|ui| {
                            ui.add_enabled_ui(!running, |ui| {
                                ui.radio_value(
                                    &mut self.timestamp,
                                    TimestampMode::RelativeSeconds,
                                    labels.ts_relative,
                                );
                                ui.radio_value(
                                    &mut self.timestamp,
                                    TimestampMode::EpochSeconds,
                                    labels.ts_epoch,
                                );
                            });
                        });
                        ui.label("");
                        ui.end_row();
                    });
            });

            ui.add_space(4.0);

            // ---- Run ----
            let ready = self.blf_path.is_some()
                && self.dbc_path.is_some()
                && self.out_dir.is_some()
                && !running;
            ui.vertical_centered_justified(|ui| {
                if ui
                    .add_enabled(
                        ready,
                        egui::Button::new(egui::RichText::new(labels.convert).size(16.0))
                            .min_size([0.0, 36.0].into()),
                    )
                    .clicked()
                {
                    self.start_conversion();
                }
            });

            match &self.state {
                State::Idle => {}
                State::Running { progress, .. } => {
                    ui.add(
                        egui::ProgressBar::new(progress.fraction())
                            .show_percentage()
                            .animate(true),
                    );
                    ui.label(format!(
                        "{} {} {}",
                        labels.converting, progress.frames_read, labels.frames_unit
                    ));
                }
                State::Done(summary) => {
                    ui.colored_label(
                        egui::Color32::from_rgb(0x2e, 0x7d, 0x32),
                        (labels.done)(summary),
                    );
                    if let Some(dir) = summary.output_path.parent()
                        && ui.button(labels.open_folder).clicked()
                    {
                        open_in_file_manager(dir);
                    }
                }
                State::Failed(message) => {
                    ui.colored_label(
                        egui::Color32::from_rgb(0xc6, 0x28, 0x28),
                        format!("{}{}", labels.error_prefix, message),
                    );
                }
            }
        });
    }
}

/// Open a folder in the platform file manager (best effort).
fn open_in_file_manager(dir: &Path) {
    #[cfg(target_os = "windows")]
    let command = "explorer";
    #[cfg(target_os = "macos")]
    let command = "open";
    #[cfg(all(not(target_os = "windows"), not(target_os = "macos")))]
    let command = "xdg-open";
    let _ = std::process::Command::new(command).arg(dir).spawn();
}
